#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Stable Extension Distribution Pipeline
on:
  pull_request:
    branches:
      - v1.1.0
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  push:
    branches:
      - v1.1.0
    paths-ignore:
      - '**/README.md'
      - 'doc/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@v1.1.0
    with:
      duckdb_version: v1.1.0
      extension_name: spatial
      exclude_archs: 'windows_amd64;windows_amd64_rtools'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_deploy.yml@v1.1.0
    secrets: inherit
    with:
      duckdb_version: v1.1.0
      extension_name: spatial
      exclude_archs: 'windows_amd64;windows_amd64_rtools'
      deploy_latest: 'true'
