name: DuckDB-Wasm extensions
on:
  workflow_dispatch:
    inputs:
      # Git ref of the duckdb repo
      duckdb_tag:
        type: string
      # Git ref of the duckdb repo
      platforms:
        required: false
        default: '["wasm_mvp", "wasm_eh", "wasm_threads"]'
        type: string
      # Publish extensions on extensions.duckdb.org?
      release_s3:
        required: true
        type: boolean
        default: false

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  build_wasm:
    name: Build extensions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        duckdb_wasm_arch: ${{ fromJSON(github.event.inputs.platforms) }}
    env:
      VCPKG_TOOLCHAIN_PATH: ${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake
      DUCKDB_PLATFORM: "${{ matrix.duckdb_wasm_arch }}"

    steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  submodules: true

            - uses: mymindstorm/setup-emsdk@v12
              with:
                  version: 'latest'

            - name: Install
              shell: bash
              run: sudo apt-get update -y -qq && sudo apt-get install -y -qq ninja-build

            - name: Setup vcpkg
              uses: lukka/run-vcpkg@v11.1
              with:
                  vcpkgGitCommitId: a1a1cbc975abf909a6c8985a6a2b8fe20bbd9bd6

            - name: Setup Ccache
              uses: hendrikmuhs/ccache-action@main
              with:
                  key: ${{ github.job }}-${{ matrix.duckdb_wasm_arch }}

            - name: PatchDuckDB
              run: |
                 cd duckdb
                 git tag ${{ inputs.duckdb_tag }}
                 git apply ../cmake.patch
                 cp ../extension_config_local.cmake extension/extension_config.cmake

            - name: Build Wasm module MVP
              if: ${{ matrix.duckdb_wasm_arch == 'wasm_mvp' }}
              run: |
                cd duckdb && DUCKDB_PLATFORM=wasm_mvp make wasm_mvp

            - name: Build Wasm module EH
              if: ${{ matrix.duckdb_wasm_arch == 'wasm_eh' }}
              run: |
                cd duckdb && DUCKDB_PLATFORM=wasm_eh make wasm_eh

            - name: Build Wasm module THREADS
              if: ${{ matrix.duckdb_wasm_arch == 'wasm_threads' }}
              run: |
                cd duckdb && DUCKDB_PLATFORM=wasm_threads make wasm_threads CMAKE_C_FLAGS="-pthread"

            - name: Upload artifact
              uses: actions/upload-artifact@v3
              with:
                  name: duckdb_extensions_${{ env.DUCKDB_PLATFORM }}
                  path: build/${{ matrix.duckdb_wasm_arch }}/repository/${{ inputs.duckdb_ref }}/${{ env.DUCKDB_PLATFORM }}
                  retention-days: 1
